### ISSUE TITLE
What am I doing wrong? 🤷‍♂️

### ISSUE THREAD

**Issue by steinbrueckri** [DocSystem/osx-razer-led#2]
```
./osx-razer-led info
Unable to create plugin (0xe00002be)
Unable to create plugin (0xe00002be)
Unable to create plugin (0xe00002be)
Unable to create plugin (0xe00002be)
Unable to create plugin (0xe00002be)
Unable to create plugin (0xe00002be)
```
OS: 10.15.5 (19F101)

**Comment by DocSystem** [comment]
Try recompile the source code using the terminal command ``make``

**Comment by steinbrueckri** [comment]
First of all thanks for the fast feedback! <3
I compiled the code on my own also in the first place. I have redone all steps see below.

![Bildschirmfoto 2020-06-05 um 08 48 47](https://user-images.githubusercontent.com/578303/83845562-705e6480-a709-11ea-81f7-be117a284753.png)
![Bildschirmfoto 2020-06-05 um 08 48 55](https://user-images.githubusercontent.com/578303/83845564-718f9180-a709-11ea-9789-f38eade97ca6.png)
